### PR TITLE
i think this one gonna work

### PR DESCRIPTION
**Pull request by spiritbro1**
@chunza2542 i remove my function loginWithUnstoppable and just use `login` function and added a condition to it i think this one gonna work, feel free to merge whenever you're free

### CODE REVIEW

**Comment by chunza2542** [comment]
Ohh, so sorry for the late reply but let me try this first
https://github.com/chunza2542/ethtalk.app/pull/2#discussion_r803559530

**Comment by spiritbro1** [comment]
> Ohh, so sorry for the late reply but let me try this first [#2 (comment)](https://github.com/chunza2542/ethtalk.app/pull/2#discussion_r803559530)

no problem bro

**Comment by chunza2542** [comment]
@spiritbro1 Deployed, could you try it again?

**Comment by spiritbro1** [comment]
image

still the same bro 🥲

**Comment by chunza2542** [comment]
Hey, after some debugging, I still don't know what cause the problem but if you would like to help me debug you can send me your email and I'll put you as an Editor (firebase). -> Twitter: @chunza2542.

**Pull request merged**
